apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka

resources:
  - namespace.yaml
  - strimzi-operator.yaml
  - kafka-metrics-configmap.yaml
  - kafka-controller-nodepool.yaml
  - kafka-broker-nodepool.yaml
  - kafka-cluster.yaml
